### ISSUE TITLE
Unknown version 2 for vpk

### ISSUE THREAD

**Issue by Areng14** [ValvePython/vpk#30]
![image](https://user-images.githubusercontent.com/97821562/168829535-903d7c77-a58d-4712-a99e-32a92d7aa073.png)

I got an error code saying that  Unknown verson 2 for vpk

**Comment by nitzan-blink** [comment]
https://github.com/ValvePython/vpk/issues/25#issuecomment-1120194487

**Comment by rossengeorgiev** [comment]
The project doesn't have a gui, so probably the wrong place to raise this issue

**Comment by nitzan-blink** [comment]
@rossengeorgiev what do you mean?
I came across the same issue, because by default this library produces version 2 for the vpk.
the solution is to specify the -cv flag in your comment that I linked to.

**Comment by rossengeorgiev** [comment]
Above is gui error from windows, and looks like attempting to open a file. There is no more info beyond that.

**Comment by nitzan-blink** [comment]
I can fill in the info, the OP tried to use your library with default settings to create a .vpk file.
when he tried to run it with Portal 2, the game wouldn't start because it is expecting a v1 vpk (while the library produces v2 by default).
so to solve his problem, he needs to use "-cv 1", and that's what I was trying to explain
